
platform :ios, '8.0'
inhibit_all_warnings!
target 'Buggy' do
    # 友盟分享基础依赖库
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    # 友盟分享对应平台
    pod 'UMCShare/Social/ReducedWeChat'    # 精简版微信
    pod 'UMCShare/Social/ReducedQQ'        # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedSina'      # 集成新浪微博(精简版1M)

    pod 'AFNetworking'
    pod 'MagicalRecord', '~> 2.3.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'TMCache', '~> 2.1.0'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'Masonry'
    pod 'MMPopupView', '~> 1.7'
    pod 'DZNEmptyDataSet', '~> 1.7.2'
    pod 'SDWebImage'
    pod 'pop'
    pod 'FMDB'
    pod 'FMDBHelpers'
    pod 'UICountingLabel', '~> 1.2.0'
#    pod 'Bugtags'
# FSCalender不要更新
    pod 'FSCalendar'
    pod 'FreeStreamer'
    pod 'lottie-ios'
    pod 'MJExtension'
end

#Using AFNetworking (3.1.0)
#Using AMap2DMap (4.2.0)
#Using AMapFoundation (1.2.0)
#Using AMapSearch (4.2.0)
#Using AVOSCloud (7.3.2)
#Using AVOSCloudCrashReporting (7.3.2)
#Using AVOSCloudIM (7.3.2)
#Using DZNEmptyDataSet (1.7.3)
#Using FMDB (2.6.2)
#Using FMDBHelpers (0.0.7)
#Using FSCalendar (2.7.9)
#Using FreeStreamer (3.8.2)
#Using LeanCloudSocial (1.0.0-beta3)
#Using MBProgressHUD (0.9.2)
#Installing MJExtension (3.0.13)
#Using MJRefresh (3.1.12)
#Using MMPopupView (1.7.2)
#Using MagicalRecord (2.3.2)
#Using Masonry (1.0.1)
#Using Reachability (3.2)
#Using SDWebImage (4.0.0)
#Using TMCache (2.1.0)
#Using UICountingLabel (1.2.0)
#Using lottie-ios (2.1.5)
#Using pop (1.0.9)


